imports:
    - { resource: services.yml }

framework:
    secret: '%env(APPLICATION_KERNEL_SECRET)%'
    templating:
        engines: ['twig']
    router:
        resource: "%kernel.project_dir%/config/routing.yml"

swiftmailer:
    url: '%env(APPLICATION_SMTP_URL)%'

doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        connections:
            mailer:
                url: '%env(APPLICATION_DOCTRINE_DBAL_URL)%'
                server_version: 8.0
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        entity_managers:
            template:
                connection: mailer
                mappings:
                    template:
                        type:     yml
                        dir:      '%kernel.project_dir%/src/Port/Adapter/Persistence/Template/DoctrineMapping'
                        prefix:   GamingPlatform\Mailer\Domain

monolog:
    handlers:
        application_error:
            type: stream
            path: "php://stderr"
            level: error
