imports:
    - { resource: services.yml }

framework:
    secret: '%env(APPLICATION_KERNEL_SECRET)%'
    templating:
        engines: ['twig']
    router:
        resource: "%kernel.project_dir%/config/routing.yml"

doctrine:
    dbal:
        connections:
            mailer:
                url: '%env(APPLICATION_DOCTRINE_DBAL_URL)%'
                server_version: 8.0
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

monolog:
    handlers:
        application_error:
            type: stream
            path: "php://stderr"
            level: error
