deliver_mail:
    path: /
    methods:
        - POST
    defaults:
        _controller: mail-controller:deliverAction

remove_template_revision:
    path: /templates/{name}/revisions/{revisionId}
    methods:
        - DELETE
    defaults:
        _controller: template-controller:removeTemplateRevisionAction
