services:

    mail-controller:
        class: GamingPlatform\Mailer\Port\Adapter\Http\MailController
        arguments:
            - '@mail-service'
        tags:
            - 'controller.service_arguments'

    template-controller:
        class: GamingPlatform\Mailer\Port\Adapter\Http\TemplateController
        arguments:
            - '@template-service'
        tags:
            - 'controller.service_arguments'

    overwrite-with-import-command:
        class: GamingPlatform\Mailer\Port\Adapter\Console\OverwriteWithImportCommand
        arguments:
            - '@template-service'
            - '%kernel.project_dir%/import'
        tags:
            -  { name: console.command }

    mail-service:
        class: GamingPlatform\Mailer\Application\MailService
        arguments:
            - '@layouts'
            - '@templates'
            - '@template-engine'
            - '@postman'

    template-service:
        class: GamingPlatform\Mailer\Application\TemplateService
        arguments:
            - '@layouts'
            - '@templates'

    template-engine:
        class: GamingPlatform\Mailer\Port\Adapter\TemplateEngine\TwigTemplateEngine
        arguments:
            - '@twig'

    templates:
        class: GamingPlatform\Mailer\Port\Adapter\Persistence\Template\DoctrineTemplates
        arguments:
            - '@doctrine.orm.template_entity_manager'

    layouts:
        class: GamingPlatform\Mailer\Port\Adapter\Persistence\Template\DoctrineLayouts
        arguments:
            - '@doctrine.orm.template_entity_manager'

    postman:
        class: GamingPlatform\Mailer\Port\Adapter\Postman\SwiftMailerPostman
        arguments:
            - '@swiftmailer.mailer'
