services:

    mail-controller:
        class: GamingPlatform\Mailer\Port\Adapter\Http\MailController
        arguments:
            - '@mail-service'
        tags:
            - 'controller.service_arguments'

    mail-service:
        class: GamingPlatform\Mailer\Application\MailService
        arguments:
            - '@templates'
            - '@template-engine'
            - '@postman'

    template-engine:
        class: GamingPlatform\Mailer\Port\Adapter\TemplateEngine\TwigTemplateEngine
        arguments:
            - '@twig'

    templates:
        class: GamingPlatform\Mailer\Port\Adapter\Persistence\Template\DoctrineTemplates
        arguments:
            - '@doctrine.orm.template_entity_manager'

    postman:
        class: GamingPlatform\Mailer\Port\Adapter\Postman\SwiftMailerPostman
        arguments:
            - '@swiftmailer.mailer'
