services:

    mail-controller:
        class: GamingPlatform\Mailer\Port\Adapter\Http\MailController
        arguments:
            - '@mail-service'
        tags:
            - 'controller.service_arguments'

    mail-service:
        class: GamingPlatform\Mailer\Application\MailService
        arguments:
            - '@templates'
            - '@template-engine'

    template-engine:
        class: GamingPlatform\Mailer\Port\Adapter\TemplateEngine\TwigTemplateEngine
        arguments:
            - '@twig'

    templates:
        class: GamingPlatform\Mailer\Port\Adapter\Persistence\Template\DummyTemplates
